services:
  - type: web
    name: chat-with-files
    env: python
    plan: free  # or 'starter' if you upgrade
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run your_script.py --server.port=$PORT --server.address=0.0.0.0
